ansible_host_key_checking: False
ansible_ssh_user: admin
ansible_ssh_pass: admin
ansible_ssh_common_args: '-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
ansible_network_os: sros
ansible_connection: netconf
ansible_host_key_auto_add: yes


version: '{{ vsim_release }}'
vmname: '{{ inventory_hostname }}'
uuid: "{{ vsim_uuid }}"
yang_dir: /root/files/{{ vsim_release }}
license_dir: /root/files/{{ vsim_release }}
image_dir: /root/files/{{ vsim_release }}

bridge: virbr0


mgmt_ip: '{{ ansible_host }}'
mgmt_netmask: 24
mgmt_gateway: 10.199.199.1
mgmt_static_route_list:
  - 0.0.0.0/1
  - 128.0.0.0/1
