- name: Getting supported YANG schemas via NETCONF from {{ inventory_hostname }}
  netconf_get:
    display: json
    filter: <netconf-state xmlns="urn:ietf:params:xml:ns:yang:ietf-netconf-monitoring"><schemas><schema/></schemas></netconf-state>
    lock: never
  register: all_supported_schemas

- name: Creating directory for YANG modules
  file:
    dest: /tmp/{{ inventory_hostname }}/YANG
    state: directory
  delegate_to: localhost

- name: 
  set_fact: 
    nokia_schemas: "{{ all_supported_schemas.output['rpc-reply'].data['netconf-state'].schemas.schema | selectattr('identifier', 'match', 'nokia') | list | to_nice_json}}"

#- name: Fetching all supported YANG modules from {{ inventory_hostname }} / {{ ansible_network_os }}
#  include_tasks: saving_yang.yml
#  loop: "{{ all_supported_schemas.output['rpc-reply'].data['netconf-state'].schemas.schema }}"

- name: Fetching Nokia only supported YANG modules from {{ inventory_hostname }} / {{ ansible_network_os }}
  include_tasks: saving_yang.yml
  loop: "{{ nokia_schemas }}"


- name: Workaround for SROS release 16.0.R41
  copy:
    src: files/16.0.R41/YANG/nokia-sros-yang-extensions.yang
    dest: /tmp/{{ inventory_hostname }}/YANG
  when: vsim_release == "16.0.R41"
  delegate_to: localhost

